### ISSUE TITLE
[Bug]: Casino Crash

### ISSUE THREAD

**Issue by mtzyyy1** [btfstudios/issue-tracker#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Casino crash when you are near/ betting on the table.

### Expected behaviour

i can bet without crashing.

### Steps to reproduce

try bet money yourself.

### Any Texture Packs? (If so list)

NVE 

### BTF User ID

10

**Comment by kerft** [comment]
Thankyou for reporting this issue, it has been fixed for future restart
