### ISSUE TITLE
[Bug]: Smoke Bombs dont work

### ISSUE THREAD

**Issue by finny-dev** [btfstudios/issue-tracker#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I get Smoke Bombs from PD Armoury i cant pull them out and they dont have any name.

### Expected behaviour

They come out and are throwable

### Steps to reproduce

1. Buy a Smoke Bomb from PD Large
2. Try pull it out

### BTF User ID

18

**Comment by kerft** [comment]
Thankyou for reporting this issue, it has been fixed for future restart
