### ISSUE TITLE
[Bug]: Buckets dont work

### ISSUE THREAD

**Issue by finny-dev** [btfstudios/issue-tracker#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Everyones buckets get fucked up after doing certain things.

### Expected behaviour

Everyone stays in bucket 0 unless in wager etc etc.

### Steps to reproduce

1. Play server for a while, you will start to realise peoples buckets are getting fucked after a bit.

### BTF User ID

18

**Comment by 6oa** [comment]
Thanks, this has been fixed for next restart

**Comment by 6oa** [comment]
Thanks, this has been fixed for next restart

**Comment by kerft** [comment]
Thanks, this has been fixed for next restart
