### ISSUE TITLE
[Bug]: Dont have permission in gunstores.

### ISSUE THREAD

**Issue by finny-dev** [btfstudios/issue-tracker#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I took someones /calladmin ticket and they were complaining that they couldn't buy a gun from either large arms or Platinum Large Arms in VIP, the player did have plat but like I say neither of the gunstores let him buy anything, but he could buy armour from the non plat section of VIP Gunstore.

### Expected behaviour

Permissions work correctly

### Steps to reproduce

Give yourself plat, try buy something from large or VIP Platinum Large Arms.

### BTF User ID

18

**Comment by kerft** [comment]
You need gang license to buy from large arms...
