### ISSUE TITLE
[Bug]:  False anti cheat

### ISSUE THREAD

**Issue by finny-dev** [btfstudios/issue-tracker#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unsure if this is just me but when i try ban someone, It gets stuck on Generating Ban Info, then after about 30 Seconds I get anticheat banned for type 15.

### Expected behaviour

I can ban without getting Anticheated (I am moderator)

### Steps to reproduce

Put yourself as Moderator and try ban someone, - Unsure if its just moderators, or just me but yeah.

### BTF User ID

18

**Comment by kerft** [comment]
Thanks, this issue has been fixed for next restart
